name: Compile Hip

on:
  workflow_dispatch:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.10

    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: compile
      run: | 
        cl src/gpudemo.cpp /Fe:spark /std:c++latest
