name: Compile Hip

on:
  workflow_dispatch:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    
    steps:
    - name: Get OpenCL Headers
      uses: actions/checkout@v3
      with:
        repository: KhronosGroup/OpenCL-Headers
        
    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1.4.1
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: T1
      run: | 
        ls -l
    - name: T2
      run: | 
        ls -l ./..
    - name: T3
      run: | 
        ls -l ./../..
    - name: compile
      run: | 
        cl /I external/OpenCL-Headers src/gpudemo.cpp /Fe:project /std:c++latest

